# Generated by Django 3.2.4 on 2021-08-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210802_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
