# Generated by Django 3.2.4 on 2021-08-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='feedback',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
